### PR TITLE
Fix: Invalid Token for ::/ and ::/<symbol>

### LINKED ISSUE #214: `:/` evaluates to `:`
FWIW [edn spec](https://github.com/edn-format/edn?tab=readme-ov-file#keywords) says this is an invalid edn keyword.

```clojure
;; jank
clojure.core=> :/
:
clojure.core=> (name :/)
""

;; clojure
user=> :/
:/
user=> (name :/)
"/"
```

### PR DESCRIPTION
**Pull request by stmonty**
Fixes #214 

Clojure:
```
Clojure 1.12.0
user=> ::/
Syntax error reading source at (REPL:2:0).
Invalid token: ::/
user=> ::/foo
Syntax error reading source at (REPL:3:0).
Invalid token: ::/foo
```
Jank:
image

### CODE REVIEW

File: compiler+runtime/src/cpp/jank/read/lex.cpp [hunk 1]
```diff
@@ -1125,8 +1125,23 @@ namespace jank::read::lex
           if(c == ':')
           {
             ++pos;
+            auto const after_dd_colon = peek();
+            if(after_dd_colon.is_ok() && after_dd_colon.expect_ok().character == '/')
+            {
+              /* Invalid ::/ pattern found. Consume the entire invalid token. */
+              while(true)
+              {
+                auto const result = convert_to_codepoint(file.substr(pos), pos);
```
Comment (jeaye) [inline compiler+runtime/src/cpp/jank/read/lex.cpp]: Please always use direct initialization (same with line 1128).

**Review by jeaye — CHANGES_REQUESTED** [review]
Thanks, Monty. Just a stylistic fix required.
