### PR TITLE
Fix: Symbols starting with '--'

### LINKED ISSUE #198: Symbol cannot start with `--`
```clojure
clojure.core=> (def --a 1)
Read error (5 - 6): invalid number
clojure.core=> --
Read error (0 - 1): invalid number
```

### PR DESCRIPTION
**Pull request by stmonty**
Fixes #198

### CODE REVIEW

File: compiler+runtime/test/cpp/jank/read/lex.cpp [hunk 1]
```diff
@@ -1496,6 +1496,16 @@ namespace jank::read::lex
...
 
+      SUBCASE("Symbol with double hyphen")
+      {
+        processor p{ "--a" };
+        native_vector<jtl::result<token, error_ref>> const tokens(p.begin(), p.end());
+        CHECK(tokens
+              == make_results({
+                token{ 0, 3, token_kind::symbol, "--a" }
+        }));
+      }
```
Comment (jeaye) [inline compiler+runtime/test/cpp/jank/read/lex.cpp]: Just for my own sanity, would you mind adding one for `--`?

**Comment by jeaye** [comment]
Nice work, Monty!
